# https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages
name: Publish to NPM and GHCR

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # Install dependencies
      - run: rustup component add clippy
      - run: cargo install cargo-machete

      # Run tests
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo machete

  publish-npm:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # Setup .npmrc file to publish to NPM
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      # Install wasm-pack and build
      - run: cargo install wasm-pack
      - run: wasm-pack build --release --target bundler

      - name: Publish to NPM
        run: npm publish ./pkg --access public # Setup-node creates .npmrc at root, but pkg has the actual package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
  publish-ghcr:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # Setup .npmrc file to publish to GHCR
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@NoelleStern"

      # Install wasm-pack and build
      - run: cargo install wasm-pack
      - run: wasm-pack build --release --target bundler

      # Edit package.json
      - run: npm pkg set name="@NoelleStern/RMPP" publishConfig.registry="https://npm.pkg.github.com"
        working-directory: ./pkg

      - name: Publish to GHCR
        run: npm publish ./pkg # Setup-node creates .npmrc at root, but pkg has the actual package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}